apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: image-service-controller
  name: image-service-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service-controller
  template:
    metadata:
      labels:
        app: image-service-controller
    spec:
      containers:
      - image: docker.io/microyui/imageservicecontroller:1.6
        name: image-service-controller
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: image-service-controller-service
  namespace: default
spec:
  selector:
    app: image-service-controller
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32610
  type: NodePort